# Generated by Django 5.0.4 on 2024-04-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Enter phone number', max_length=20, unique=True, verbose_name='phone number'),
        ),
    ]
