# Generated by Django 5.0.4 on 2024-07-05 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lesson_description_lesson_photo_lessonnotes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonnotes',
            options={'verbose_name_plural': 'lesson notes'},
        ),
    ]
