# Generated by Django 5.0.4 on 2024-07-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_lesson_id_lessonnotes_lesson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='notes',
        ),
        migrations.AddField(
            model_name='lesson',
            name='notes',
            field=models.ManyToManyField(through='core.LessonNotes', to='core.student'),
        ),
    ]
