# Generated by Django 5.0.4 on 2024-07-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_student_notes_lesson_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='notes',
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.ManyToManyField(through='core.LessonNotes', to='core.lesson'),
        ),
    ]
