# Generated by Django 5.0.4 on 2024-07-05 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_lesson_notes_student_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonnotes',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hhh', to='core.lesson'),
        ),
    ]
