# Generated by Django 5.0.4 on 2024-07-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/photos/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/photos/'),
        ),
    ]
