# Generated by Django 5.0.4 on 2024-07-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_instructor_photo_alter_lesson_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomExam',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.exam',),
        ),
    ]
